### ISSUE TITLE
Universal highlighter 

### ISSUE THREAD

**Issue by AnEmortalKid** [ThomasHickman/language-dogescript#2]
Howdy! I was wondering if there was interest from the owners or this repo in helping us out with a highlighter that supports multiple editors: https://github.com/dogescript/dogescript/issues/95#issuecomment-427350261

I personally use the atom one and it’s worked pretty nicely. Having something within the dogescript organization would allow us to also keep support a bit more closer for the highlighter when new keywords or features get added.

**Comment by ThomasHickman** [comment]
^ answered in the issue linked above :)
